server {
    listen       80 default_server;
    listen  [::]:80 default_server;
    server_name  localhost;

    location / {
        root   /keygen/web;
        index  index.html index.htm;
    }

    location /gen {
        proxy_pass   http://127.0.0.1:8080;
    }
}
